export const STATIC_LEADERBOARD_META = {
  "games_played": 32
};

export const STATIC_BEST_LEADERBOARD = [
  {
    "rank": 1,
    "user_id": 3,
    "display_name": "Jerry's Money Ball",
    "title": "Jerry's Money Ball",
    "score": 270,
    "total": 270,
    "total_possible": 680,
    "x": 27,
    "y": 32,
    "pct": 0.8438,
    "entries": 1,
    "challenge": "best",
    "champion": "Michigan"
  },
  {
    "rank": 1,
    "user_id": 2,
    "display_name": "Like No One Ever Was",
    "title": "Like No One Ever Was",
    "score": 270,
    "total": 270,
    "total_possible": 1250,
    "x": 27,
    "y": 32,
    "pct": 0.8438,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 1,
    "user_id": 15,
    "display_name": "The Builder",
    "title": "The Builder",
    "score": 270,
    "total": 270,
    "total_possible": 640,
    "x": 27,
    "y": 32,
    "pct": 0.8438,
    "entries": 1,
    "challenge": "best",
    "champion": "Arizona"
  },
  {
    "rank": 4,
    "user_id": 96,
    "display_name": "Bracket 1",
    "title": "Bracket 1",
    "score": 260,
    "total": 260,
    "total_possible": 670,
    "x": 26,
    "y": 32,
    "pct": 0.8125,
    "entries": 1,
    "challenge": "best",
    "champion": "Michigan St"
  },
  {
    "rank": 4,
    "user_id": 3,
    "display_name": "Green Jacket Bracket",
    "title": "Green Jacket Bracket",
    "score": 260,
    "total": 260,
    "total_possible": 670,
    "x": 26,
    "y": 32,
    "pct": 0.8125,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 4,
    "user_id": 85,
    "display_name": "Henry's amazing bracket",
    "title": "Henry's amazing bracket",
    "score": 260,
    "total": 260,
    "total_possible": 680,
    "x": 26,
    "y": 32,
    "pct": 0.8125,
    "entries": 1,
    "challenge": "best",
    "champion": "Arizona"
  },
  {
    "rank": 4,
    "user_id": 99,
    "display_name": "Perfection",
    "title": "Perfection",
    "score": 260,
    "total": 260,
    "total_possible": 670,
    "x": 26,
    "y": 32,
    "pct": 0.8125,
    "entries": 1,
    "challenge": "best",
    "champion": "Arizona"
  },
  {
    "rank": 4,
    "user_id": 1,
    "display_name": "RH 2nd Bracket",
    "title": "RH 2nd Bracket",
    "score": 260,
    "total": 260,
    "total_possible": 720,
    "x": 26,
    "y": 32,
    "pct": 0.8125,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 9,
    "user_id": 108,
    "display_name": "Jschultz",
    "title": "Jschultz",
    "score": 250,
    "total": 250,
    "total_possible": 1220,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "best",
    "champion": ""
  },
  {
    "rank": 9,
    "user_id": 2,
    "display_name": "Lets Win",
    "title": "Lets Win",
    "score": 250,
    "total": 250,
    "total_possible": 1280,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 9,
    "user_id": 2,
    "display_name": "Purdue",
    "title": "Purdue",
    "score": 250,
    "total": 250,
    "total_possible": 680,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 9,
    "user_id": 2,
    "display_name": "Robby Brackets",
    "title": "Robby Brackets",
    "score": 250,
    "total": 250,
    "total_possible": 680,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 9,
    "user_id": 75,
    "display_name": "The main one for the best bracket",
    "title": "The main one for the best bracket",
    "score": 250,
    "total": 250,
    "total_possible": 660,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "best",
    "champion": "Michigan"
  },
  {
    "rank": 9,
    "user_id": 2,
    "display_name": "Top of the Leaderboard",
    "title": "Top of the Leaderboard",
    "score": 250,
    "total": 250,
    "total_possible": 680,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 9,
    "user_id": 2,
    "display_name": "fd",
    "title": "fd",
    "score": 250,
    "total": 250,
    "total_possible": 680,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "best",
    "champion": "Arizona"
  },
  {
    "rank": 16,
    "user_id": 3,
    "display_name": "All I Do Is Win",
    "title": "All I Do Is Win",
    "score": 240,
    "total": 240,
    "total_possible": 660,
    "x": 24,
    "y": 32,
    "pct": 0.75,
    "entries": 1,
    "challenge": "best",
    "champion": "UConn"
  },
  {
    "rank": 16,
    "user_id": 1,
    "display_name": "Blue",
    "title": "Blue",
    "score": 240,
    "total": 240,
    "total_possible": 680,
    "x": 24,
    "y": 32,
    "pct": 0.75,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 16,
    "user_id": 9,
    "display_name": "Cam Picks 1",
    "title": "Cam Picks 1",
    "score": 240,
    "total": 240,
    "total_possible": 710,
    "x": 24,
    "y": 32,
    "pct": 0.75,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 16,
    "user_id": 97,
    "display_name": "Carson pro bracket",
    "title": "Carson pro bracket",
    "score": 240,
    "total": 240,
    "total_possible": 660,
    "x": 24,
    "y": 32,
    "pct": 0.75,
    "entries": 1,
    "challenge": "best",
    "champion": "Michigan"
  },
  {
    "rank": 16,
    "user_id": 2,
    "display_name": "Harlow's Hurricanes",
    "title": "Harlow's Hurricanes",
    "score": 240,
    "total": 240,
    "total_possible": 670,
    "x": 24,
    "y": 32,
    "pct": 0.75,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 16,
    "user_id": 1,
    "display_name": "Robby\u2019s First Impression Bracket",
    "title": "Robby\u2019s First Impression Bracket",
    "score": 240,
    "total": 240,
    "total_possible": 680,
    "x": 24,
    "y": 32,
    "pct": 0.75,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 22,
    "user_id": 76,
    "display_name": "Donovan Dent in the Tournoment",
    "title": "Donovan Dent in the Tournoment",
    "score": 230,
    "total": 230,
    "total_possible": 670,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "best",
    "champion": "Michigan"
  },
  {
    "rank": 22,
    "user_id": 3,
    "display_name": "DrJ's Dunk Tank",
    "title": "DrJ's Dunk Tank",
    "score": 230,
    "total": 230,
    "total_possible": 700,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 22,
    "user_id": 3,
    "display_name": "Dude Wipes",
    "title": "Dude Wipes",
    "score": 230,
    "total": 230,
    "total_possible": 640,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "best",
    "champion": "Michigan"
  },
  {
    "rank": 22,
    "user_id": 1,
    "display_name": "Lets Chalk About It",
    "title": "Lets Chalk About It",
    "score": 230,
    "total": 230,
    "total_possible": 680,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 22,
    "user_id": 1,
    "display_name": "Solid Shot",
    "title": "Solid Shot",
    "score": 230,
    "total": 230,
    "total_possible": 710,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 22,
    "user_id": 2,
    "display_name": "Twice is Nice",
    "title": "Twice is Nice",
    "score": 230,
    "total": 230,
    "total_possible": 620,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "best",
    "champion": "Florida"
  },
  {
    "rank": 22,
    "user_id": 90,
    "display_name": "Winner Winner Chicken Dinner",
    "title": "Winner Winner Chicken Dinner",
    "score": 230,
    "total": 230,
    "total_possible": 680,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 29,
    "user_id": 2,
    "display_name": "D or an F",
    "title": "D or an F",
    "score": 220,
    "total": 220,
    "total_possible": 670,
    "x": 22,
    "y": 32,
    "pct": 0.6875,
    "entries": 1,
    "challenge": "best",
    "champion": "Florida"
  },
  {
    "rank": 29,
    "user_id": 1,
    "display_name": "Winnerwinnerchickendinner",
    "title": "Winnerwinnerchickendinner",
    "score": 220,
    "total": 220,
    "total_possible": 670,
    "x": 22,
    "y": 32,
    "pct": 0.6875,
    "entries": 1,
    "challenge": "best",
    "champion": "Duke"
  },
  {
    "rank": 31,
    "user_id": 2,
    "display_name": "ufl",
    "title": "ufl",
    "score": 210,
    "total": 210,
    "total_possible": 650,
    "x": 21,
    "y": 32,
    "pct": 0.6562,
    "entries": 1,
    "challenge": "best",
    "champion": "Florida"
  },
  {
    "rank": 32,
    "user_id": 2,
    "display_name": "lville",
    "title": "lville",
    "score": 170,
    "total": 170,
    "total_possible": 570,
    "x": 17,
    "y": 32,
    "pct": 0.5312,
    "entries": 1,
    "challenge": "best",
    "champion": "Louisville"
  },
  {
    "rank": 33,
    "user_id": 1,
    "display_name": "Onions",
    "title": "Onions",
    "score": 100,
    "total": 100,
    "total_possible": 610,
    "x": 10,
    "y": 32,
    "pct": 0.3125,
    "entries": 1,
    "challenge": "best",
    "champion": "Queens"
  },
  {
    "rank": 34,
    "user_id": 2,
    "display_name": "The Bad Bracket",
    "title": "The Bad Bracket",
    "score": 50,
    "total": 50,
    "total_possible": 1730,
    "x": 5,
    "y": 32,
    "pct": 0.1562,
    "entries": 1,
    "challenge": "best",
    "champion": "Siena"
  }
];

export const STATIC_WORST_LEADERBOARD = [
  {
    "rank": 1,
    "user_id": 2,
    "display_name": "Lehigh is Back",
    "title": "Lehigh is Back",
    "score": 270,
    "total": 270,
    "total_possible": 660,
    "x": 27,
    "y": 32,
    "pct": 0.8438,
    "entries": 1,
    "challenge": "worst",
    "champion": "Lehigh/Prairie View"
  },
  {
    "rank": 1,
    "user_id": 2,
    "display_name": "The Stra",
    "title": "The Stra",
    "score": 270,
    "total": 270,
    "total_possible": 680,
    "x": 27,
    "y": 32,
    "pct": 0.8438,
    "entries": 1,
    "challenge": "worst",
    "champion": "Hofstra"
  },
  {
    "rank": 3,
    "user_id": 96,
    "display_name": "Bad Bracket",
    "title": "Bad Bracket",
    "score": 260,
    "total": 260,
    "total_possible": 660,
    "x": 26,
    "y": 32,
    "pct": 0.8125,
    "entries": 1,
    "challenge": "worst",
    "champion": "Lehigh/Prairie View"
  },
  {
    "rank": 3,
    "user_id": 108,
    "display_name": "Fins up",
    "title": "Fins up",
    "score": 260,
    "total": 260,
    "total_possible": 670,
    "x": 26,
    "y": 32,
    "pct": 0.8125,
    "entries": 1,
    "challenge": "worst",
    "champion": "LIU"
  },
  {
    "rank": 3,
    "user_id": 2,
    "display_name": "Potato",
    "title": "Potato",
    "score": 260,
    "total": 260,
    "total_possible": 650,
    "x": 26,
    "y": 32,
    "pct": 0.8125,
    "entries": 1,
    "challenge": "worst",
    "champion": "Idaho"
  },
  {
    "rank": 6,
    "user_id": 90,
    "display_name": "Another one bites the dust",
    "title": "Another one bites the dust",
    "score": 250,
    "total": 250,
    "total_possible": 700,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "worst",
    "champion": "Hawaii"
  },
  {
    "rank": 6,
    "user_id": 75,
    "display_name": "worst",
    "title": "worst",
    "score": 250,
    "total": 250,
    "total_possible": 680,
    "x": 25,
    "y": 32,
    "pct": 0.7812,
    "entries": 1,
    "challenge": "worst",
    "champion": "Siena"
  },
  {
    "rank": 8,
    "user_id": 76,
    "display_name": "Fins Up",
    "title": "Fins Up",
    "score": 240,
    "total": 240,
    "total_possible": 690,
    "x": 24,
    "y": 32,
    "pct": 0.75,
    "entries": 1,
    "challenge": "worst",
    "champion": "Siena"
  },
  {
    "rank": 8,
    "user_id": 2,
    "display_name": "The Bad Bracket",
    "title": "The Bad Bracket",
    "score": 240,
    "total": 240,
    "total_possible": 1820,
    "x": 24,
    "y": 32,
    "pct": 0.75,
    "entries": 1,
    "challenge": "worst",
    "champion": "Siena"
  },
  {
    "rank": 10,
    "user_id": 95,
    "display_name": "Fins up",
    "title": "Fins up",
    "score": 230,
    "total": 230,
    "total_possible": 660,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "worst",
    "champion": "LIU"
  },
  {
    "rank": 10,
    "user_id": 3,
    "display_name": "No Winners",
    "title": "No Winners",
    "score": 230,
    "total": 230,
    "total_possible": 640,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "worst",
    "champion": "UMBC/Howard"
  },
  {
    "rank": 10,
    "user_id": 1,
    "display_name": "Perfectly Wrong",
    "title": "Perfectly Wrong",
    "score": 230,
    "total": 230,
    "total_possible": 1820,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "worst",
    "champion": "Siena"
  },
  {
    "rank": 10,
    "user_id": 94,
    "display_name": "Worst",
    "title": "Worst",
    "score": 230,
    "total": 230,
    "total_possible": 660,
    "x": 23,
    "y": 32,
    "pct": 0.7188,
    "entries": 1,
    "challenge": "worst",
    "champion": "LIU"
  },
  {
    "rank": 14,
    "user_id": 2,
    "display_name": "It's P View's Year",
    "title": "It's P View's Year",
    "score": 220,
    "total": 220,
    "total_possible": 1220,
    "x": 22,
    "y": 32,
    "pct": 0.6875,
    "entries": 1,
    "challenge": "worst",
    "champion": "Lehigh/Prairie View"
  },
  {
    "rank": 14,
    "user_id": 1,
    "display_name": "Onions",
    "title": "Onions",
    "score": 220,
    "total": 220,
    "total_possible": 630,
    "x": 22,
    "y": 32,
    "pct": 0.6875,
    "entries": 1,
    "challenge": "worst",
    "champion": "Queens"
  },
  {
    "rank": 14,
    "user_id": 2,
    "display_name": "PENN",
    "title": "PENN",
    "score": 220,
    "total": 220,
    "total_possible": 640,
    "x": 22,
    "y": 32,
    "pct": 0.6875,
    "entries": 1,
    "challenge": "worst",
    "champion": "Penn"
  },
  {
    "rank": 17,
    "user_id": 2,
    "display_name": "Queens",
    "title": "Queens",
    "score": 210,
    "total": 210,
    "total_possible": 710,
    "x": 21,
    "y": 32,
    "pct": 0.6562,
    "entries": 1,
    "challenge": "worst",
    "champion": "Queens"
  },
  {
    "rank": 17,
    "user_id": 1,
    "display_name": "The Dog",
    "title": "The Dog",
    "score": 210,
    "total": 210,
    "total_possible": 670,
    "x": 21,
    "y": 32,
    "pct": 0.6562,
    "entries": 1,
    "challenge": "worst",
    "champion": "Siena"
  },
  {
    "rank": 19,
    "user_id": 85,
    "display_name": "BEST WORST BRACKET",
    "title": "BEST WORST BRACKET",
    "score": 180,
    "total": 180,
    "total_possible": 680,
    "x": 18,
    "y": 32,
    "pct": 0.5625,
    "entries": 1,
    "challenge": "worst",
    "champion": "Siena"
  },
  {
    "rank": 20,
    "user_id": 2,
    "display_name": "Johnny",
    "title": "Johnny",
    "score": 160,
    "total": 160,
    "total_possible": 630,
    "x": 16,
    "y": 32,
    "pct": 0.5,
    "entries": 1,
    "challenge": "worst",
    "champion": "High Point"
  },
  {
    "rank": 21,
    "user_id": 1,
    "display_name": "Worst Bad Bracket",
    "title": "Worst Bad Bracket",
    "score": 110,
    "total": 110,
    "total_possible": 660,
    "x": 11,
    "y": 32,
    "pct": 0.3438,
    "entries": 1,
    "challenge": "worst",
    "champion": "Saint Louis"
  },
  {
    "rank": 22,
    "user_id": 1,
    "display_name": "Solid Shot",
    "title": "Solid Shot",
    "score": 80,
    "total": 80,
    "total_possible": 590,
    "x": 8,
    "y": 32,
    "pct": 0.25,
    "entries": 1,
    "challenge": "worst",
    "champion": "Duke"
  },
  {
    "rank": 23,
    "user_id": 1,
    "display_name": "RH 2nd Bracket",
    "title": "RH 2nd Bracket",
    "score": 50,
    "total": 50,
    "total_possible": 590,
    "x": 5,
    "y": 32,
    "pct": 0.1562,
    "entries": 1,
    "challenge": "worst",
    "champion": "Duke"
  },
  {
    "rank": 24,
    "user_id": 2,
    "display_name": "Official?",
    "title": "Official?",
    "score": 10,
    "total": 10,
    "total_possible": 620,
    "x": 1,
    "y": 32,
    "pct": 0.0312,
    "entries": 1,
    "challenge": "worst",
    "champion": "UConn"
  },
  {
    "rank": 25,
    "user_id": 85,
    "display_name": "WorstbracketOf All time",
    "title": "WorstbracketOf All time",
    "score": 0,
    "total": 0,
    "total_possible": 2280,
    "x": 0,
    "y": 32,
    "pct": 0.0,
    "entries": 1,
    "challenge": "worst",
    "champion": "LIU"
  }
];
